name = "fresh-expense"
main = "src/index.ts"
compatibility_date = "2024-03-01"

[env.production]
workers_dev = true
route = "fresh-expense.com/*"

[env.staging]
workers_dev = true
route = "staging.fresh-expense.com/*"

[vars]
ENVIRONMENT = "production"
API_URL = "https://api.tallyup.com"
WEBHOOK_URL = "https://api.tallyup.com/webhooks/tallyup"
MONGODB_URI = { secret = true }
MONGODB_DB = "expense_db"

[[kv_namespaces]]
binding = "USERS"
id = "users"
preview_id = "users"

[[kv_namespaces]]
binding = "TRANSACTIONS"
id = "transactions"
preview_id = "transactions"

[[kv_namespaces]]
binding = "RECEIPTS"
id = ""

[[kv_namespaces]]
binding = "MERCHANTS"
id = ""

[[kv_namespaces]]
binding = "REPORTS"
id = ""

[[kv_namespaces]]
binding = "TEMPLATES"
id = ""

[[kv_namespaces]]
binding = "SCHEDULES"
id = ""

[[kv_namespaces]]
binding = "SETTINGS"
id = ""

[[kv_namespaces]]
binding = "LOGS"
id = ""

[[kv_namespaces]]
binding = "CACHE"
id = ""

[triggers]
crons = ["0 * * * *", "0 0 * * *"]

[build]
command = "pnpm build"
watch_dir = "src"

[site]
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "fresh-expense-db"
database_id = "fresh-expense-db-id" 