name = "expense-app-api"
main = "dist/apps/backend/main.js"
compatibility_date = "2024-03-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "expense-app-api-prod"
workers_dev = false
route = { pattern = "api.expense-app.com/*", zone_id = "$CLOUDFLARE_ZONE_ID" }

[env.staging]
name = "expense-app-api-staging"
workers_dev = true

[vars]
ENVIRONMENT = "production"
API_URL = "https://api.expense-app.com"
MONGODB_DB = "expense_db"

# KV Namespaces
[[kv_namespaces]]
binding = "USERS"
id = "users"
preview_id = "users"

[[kv_namespaces]]
binding = "TRANSACTIONS"
id = "transactions"
preview_id = "transactions"

[[kv_namespaces]]
binding = "CACHE"
id = "$KV_NAMESPACE_ID"
preview_id = "$KV_PREVIEW_NAMESPACE_ID"

# R2 Storage
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "expense-files"
preview_bucket_name = "expense-files-dev"

# Build Configuration
[build]
command = "pnpm run build:backend"
watch_dir = "apps/backend/src"

# Cron Triggers
[triggers]
crons = ["0 * * * *", "0 0 * * *"] 