name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'libs/**'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
      - 'pnpm-lock.yaml'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'libs/**'
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
      - 'pnpm-lock.yaml'
      - '.github/workflows/ci.yml'

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Set PNPM_HOME
        run: |
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests and linting
        run: |
          pnpm run lint
          pnpm run test
