name: Deploy to Cloudflare

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  NODE_VERSION: '20.x'
  PNPM_VERSION: '8.15.4'
  HUGGINGFACE_API_KEY: ${{ secrets.PROD_HUGGINGFACE_API_KEY }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          missing_secrets=()

          # Check for required secrets
          [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ] && missing_secrets+=("CLOUDFLARE_API_TOKEN")
          [ -z "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ] && missing_secrets+=("CLOUDFLARE_ACCOUNT_ID")
          [ -z "${{ secrets.JWT_SECRET }}" ] && missing_secrets+=("JWT_SECRET")
          [ -z "${{ secrets.ENCRYPTION_KEY }}" ] && missing_secrets+=("ENCRYPTION_KEY")
          [ -z "${{ secrets.GMAIL_CLIENT_ID_1 }}" ] && missing_secrets+=("GMAIL_CLIENT_ID_1")
          [ -z "${{ secrets.GMAIL_CLIENT_SECRET_1 }}" ] && missing_secrets+=("GMAIL_CLIENT_SECRET_1")
          [ -z "${{ secrets.GMAIL_REFRESH_TOKEN_1 }}" ] && missing_secrets+=("GMAIL_REFRESH_TOKEN_1")
          [ -z "${{ secrets.GMAIL_CLIENT_ID_2 }}" ] && missing_secrets+=("GMAIL_CLIENT_ID_2")
          [ -z "${{ secrets.GMAIL_CLIENT_SECRET_2 }}" ] && missing_secrets+=("GMAIL_CLIENT_SECRET_2")
          [ -z "${{ secrets.GMAIL_REFRESH_TOKEN_2 }}" ] && missing_secrets+=("GMAIL_REFRESH_TOKEN_2")
          [ -z "${{ secrets.GMAIL_CLIENT_ID_3 }}" ] && missing_secrets+=("GMAIL_CLIENT_ID_3")
          [ -z "${{ secrets.GMAIL_CLIENT_SECRET_3 }}" ] && missing_secrets+=("GMAIL_CLIENT_SECRET_3")
          [ -z "${{ secrets.GMAIL_REFRESH_TOKEN_3 }}" ] && missing_secrets+=("GMAIL_REFRESH_TOKEN_3")
          [ -z "${{ secrets.GMAIL_CLIENT_ID_4 }}" ] && missing_secrets+=("GMAIL_CLIENT_ID_4")
          [ -z "${{ secrets.GMAIL_CLIENT_SECRET_4 }}" ] && missing_secrets+=("GMAIL_CLIENT_SECRET_4")
          [ -z "${{ secrets.GMAIL_REFRESH_TOKEN_4 }}" ] && missing_secrets+=("GMAIL_REFRESH_TOKEN_4")
          [ -z "${{ secrets.GMAIL_CLIENT_ID_5 }}" ] && missing_secrets+=("GMAIL_CLIENT_ID_5")
          [ -z "${{ secrets.GMAIL_CLIENT_SECRET_5 }}" ] && missing_secrets+=("GMAIL_CLIENT_SECRET_5")
          [ -z "${{ secrets.GMAIL_REFRESH_TOKEN_5 }}" ] && missing_secrets+=("GMAIL_REFRESH_TOKEN_5")
          [ -z "${{ secrets.PROD_HUGGINGFACE_API_KEY }}" ] && missing_secrets+=("PROD_HUGGINGFACE_API_KEY")
          [ -z "${{ secrets.SENDGRID_API_KEY }}" ] && missing_secrets+=("SENDGRID_API_KEY")

          if [ ${#missing_secrets[@]} -ne 0 ]; then
            echo "Error: The following required secrets are missing:"
            printf '%s\n' "${missing_secrets[@]}"
            exit 1
          fi

          echo "All required secrets are present."

      - name: Validate Hugging Face API Key
        run: |
          if ! curl -s -H "Authorization: Bearer ${{ secrets.PROD_HUGGINGFACE_API_KEY }}" https://api.huggingface.co/models/sentence-transformers/all-MiniLM-L6-v2 > /dev/null; then
            echo "Error: Invalid Hugging Face API key"
            exit 1
          fi
          echo "Hugging Face API key is valid"

  deploy-frontend:
    needs: validate-secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Verify pnpm installation
        run: |
          pnpm --version
          which pnpm

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: pnpm nx build frontend
        env:
          NODE_ENV: production
          VITE_API_URL: https://fresh-expense-api.workers.dev
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID_1 }}
          VITE_GOOGLE_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET_1 }}
          VITE_JWT_STORAGE_KEY: jwt_token

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/frontend/dist --project-name=fresh-expense

  deploy-backend:
    needs: validate-secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Verify pnpm installation
        run: |
          pnpm --version
          which pnpm

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build backend
        run: pnpm nx build backend
        env:
          NODE_ENV: production
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          GMAIL_CLIENT_ID_1: ${{ secrets.GMAIL_CLIENT_ID_1 }}
          GMAIL_CLIENT_SECRET_1: ${{ secrets.GMAIL_CLIENT_SECRET_1 }}
          GMAIL_REFRESH_TOKEN_1: ${{ secrets.GMAIL_REFRESH_TOKEN_1 }}
          GMAIL_CLIENT_ID_2: ${{ secrets.GMAIL_CLIENT_ID_2 }}
          GMAIL_CLIENT_SECRET_2: ${{ secrets.GMAIL_CLIENT_SECRET_2 }}
          GMAIL_REFRESH_TOKEN_2: ${{ secrets.GMAIL_REFRESH_TOKEN_2 }}
          GMAIL_CLIENT_ID_3: ${{ secrets.GMAIL_CLIENT_ID_3 }}
          GMAIL_CLIENT_SECRET_3: ${{ secrets.GMAIL_CLIENT_SECRET_3 }}
          GMAIL_REFRESH_TOKEN_3: ${{ secrets.GMAIL_REFRESH_TOKEN_3 }}
          GMAIL_CLIENT_ID_4: ${{ secrets.GMAIL_CLIENT_ID_4 }}
          GMAIL_CLIENT_SECRET_4: ${{ secrets.GMAIL_CLIENT_SECRET_4 }}
          GMAIL_REFRESH_TOKEN_4: ${{ secrets.GMAIL_REFRESH_TOKEN_4 }}
          GMAIL_CLIENT_ID_5: ${{ secrets.GMAIL_CLIENT_ID_5 }}
          GMAIL_CLIENT_SECRET_5: ${{ secrets.GMAIL_CLIENT_SECRET_5 }}
          GMAIL_REFRESH_TOKEN_5: ${{ secrets.GMAIL_REFRESH_TOKEN_5 }}
          PROD_HUGGINGFACE_API_KEY: ${{ secrets.PROD_HUGGINGFACE_API_KEY }}
          HUGGINGFACE_API_KEY: ${{ secrets.PROD_HUGGINGFACE_API_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy apps/backend/dist/index.js --name=fresh-expense-api
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          GMAIL_CLIENT_ID_1: ${{ secrets.GMAIL_CLIENT_ID_1 }}
          GMAIL_CLIENT_SECRET_1: ${{ secrets.GMAIL_CLIENT_SECRET_1 }}
          GMAIL_REFRESH_TOKEN_1: ${{ secrets.GMAIL_REFRESH_TOKEN_1 }}
          GMAIL_CLIENT_ID_2: ${{ secrets.GMAIL_CLIENT_ID_2 }}
          GMAIL_CLIENT_SECRET_2: ${{ secrets.GMAIL_CLIENT_SECRET_2 }}
          GMAIL_REFRESH_TOKEN_2: ${{ secrets.GMAIL_REFRESH_TOKEN_2 }}
          GMAIL_CLIENT_ID_3: ${{ secrets.GMAIL_CLIENT_ID_3 }}
          GMAIL_CLIENT_SECRET_3: ${{ secrets.GMAIL_CLIENT_SECRET_3 }}
          GMAIL_REFRESH_TOKEN_3: ${{ secrets.GMAIL_REFRESH_TOKEN_3 }}
          GMAIL_CLIENT_ID_4: ${{ secrets.GMAIL_CLIENT_ID_4 }}
          GMAIL_CLIENT_SECRET_4: ${{ secrets.GMAIL_CLIENT_SECRET_4 }}
          GMAIL_REFRESH_TOKEN_4: ${{ secrets.GMAIL_REFRESH_TOKEN_4 }}
          GMAIL_CLIENT_ID_5: ${{ secrets.GMAIL_CLIENT_ID_5 }}
          GMAIL_CLIENT_SECRET_5: ${{ secrets.GMAIL_CLIENT_SECRET_5 }}
          GMAIL_REFRESH_TOKEN_5: ${{ secrets.GMAIL_REFRESH_TOKEN_5 }}
          PROD_HUGGINGFACE_API_KEY: ${{ secrets.PROD_HUGGINGFACE_API_KEY }}
          HUGGINGFACE_API_KEY: ${{ secrets.PROD_HUGGINGFACE_API_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
